### ISSUE TITLE
[BUG] Exiting zone not start timer

### ISSUE THREAD

**Issue by daffyyyy** [surftimer/SurfTimer#465]
**Describe the bug**
Exiting the zone will not start the timer, when the zone will shrink then yes. Making a smaller zone on the edge doesn't work either

**Expected behavior**
The timer should start after leaving the zone

**Screenshots**
https://i.imgur.com/hAKusF6.mp4

**Plugin List**
```  01 "PushFix - Definitive Edition" (1.0.0) by Original idea xutaxkamay | Implementation GAMMACASE
  02 "SurfTimer Vote Extend" (1.8.3) by SurfTimer Contributors
  03 "HeadBugFix" (1.0.0) by GAMMA CASE
  04 "Basic Ban Commands" (1.10.0.6544) by AlliedModders LLC
  05 "Basic Votes" (1.10.0.6544) by AlliedModders LLC
  06 "Fun Votes" (1.10.0.6544) by AlliedModders LLC
  07 "EndTouch Fix" (1.0) by rumour, mev
  08 "SurfTimer" (1.0.dev) by All contributors
  09 "Auto exec server.cfg" (1.1) by MR. EMINEM
  10 "Basic Commands" (1.10.0.6544) by AlliedModders LLC
  11 "Player Commands" (1.10.0.6544) by AlliedModders LLC
  12 "ServerAdvertisements3" (3.3.0) by ESK0
  13 "Admin Help" (1.10.0.6544) by AlliedModders LLC
  14 "Weapon Econ Team Transfer" (1.1) by Wend4r
  15 "SurfTimer MapChooser" (2.0.0) by AlliedModders LLC & SurfTimer Contributors
  16 "Momentum surf fix '2" (1.1.3) by GAMMA CASE
  17 "Reserved Slots" (1.10.0.6544) by AlliedModders LLC
  18 "Admin Menu" (1.10.0.6544) by AlliedModders LLC
  19 "Anti-Flood" (1.10.0.6544) by AlliedModders LLC
  20 "[Surf Timer] Teleport Destination Finder" (1.0) by marcowmadeira
  21 "CS:GO Movement Unlocker" (1.0) by Peace-Maker
  22 "SurfTimer Rock The Vote" (2.0.0) by AlliedModders LLC & SurfTimer Contributors
  23 "Normalized Run Speed" (0.6) by sneaK
  24 "Client Preferences" (1.10.0.6544) by AlliedModders LLC
  25 "Basic Comm Control" (1.10.0.6544) by AlliedModders LLC
  26 "SurfTimer Nominations" (2.0.1) by AlliedModders LLC & SurfTimer Contributors
  27 "RNGFix" (1.1.2) by rio
  28 "crouchboostfix" (2.0.2) by https://github.com/t5mat
  29 "Nextmap" (1.10.0.6544) by AlliedModders LLC
  30 "Fix Hint Color Messages" (1.2.2 Franc1sco franug github version) by Phoenix (˙·٠●Феникс●٠·˙)
  31 "Basic Chat" (1.10.0.6544) by AlliedModders LLC
  32 "Sound Commands" (1.10.0.6544) by AlliedModders LLC
  33 "Fun Commands" (1.10.0.6544) by AlliedModders LLC
  34 "Admin File Reader" (1.10.0.6544) by AlliedModders LLC
  35 "Basic Info Triggers" (1.10.0.6544) by AlliedModders LLC
```

**Additional context**

**Comment by tslashd** [comment]
Was `hookzone` used for zoning the map you've showed above?
If so, I believe editing zones that have been added through `/hookzone` breaks them.

**Comment by daffyyyy** [comment]
> Was `hookzone` used for zoning the map you've showed above? If so, I believe editing zones that have been added through `/hookzone` breaks them.

After uploading the map, the zone was already created and unfortunately didn't work. Under /hookzone I can see there is 1 zone.
The map is surf_utopia_njv

**Comment by daffyyyy** [comment]
Default zones from ck_zones.sql

https://user-images.githubusercontent.com/41084667/177271070-2cf871b7-0cfc-4830-91fc-0c7cff60d5c0.mp4


Sry for laggs (geforce now)

**Comment by tslashd** [comment]
Okay did you re-zone the whole map and try again?

There is a "bug" which does not start your timer after you have just joined the server, but it's fixed by doing `sm_r` or just falling to a reset trigger on the map.

**Comment by daffyyyy** [comment]
> Okay did you re-zone the whole map and try again?
> 
> There is a "bug" which does not start your timer after you have just joined the server, but it's fixed by doing `sm_r` or just falling to a reset trigger on the map.

I didn't try to create all the zones from beginning, I edited the initial one with the thought that it would work, but only reducing it by a large part is effective. I also uploaded ck_zones.sql from scratch and the problem persists. sm_r doesn't help

**Comment by tslashd** [comment]
Not exactly sure on this (maybe @dPexxIAM could shine some light on hookzone) but I think that if you've used a hookzone the plugin always snaps to the coordinates of that given `hookzone`, so even if you edit it next time you put on the map it will snap back to it's original ones which are built into the map.

Try rezoning and see if that persists

**Comment by daffyyyy** [comment]
> Not exactly sure on this (maybe @dPexxIAM could shine some light on hookzone) but I think that if you've used a hookzone the plugin always snaps to the coordinates of that given `hookzone`, so even if you edit it the current zone, next time you put on the map it will snap back to it's original coordinates which are built into the map.
> 
> Try rezoning and see if that persists

Funny situation, it was enough to edit the hookzone and set the map type and type as start zone :D 
It looks like the zone is badly written in the .sql file, unless the hookzone comes from something else

**Comment by tslashd** [comment]
Hookzone comes from the actual `*.bsp` if I'm not mistaken

**Comment by daffyyyy** [comment]
In that case issue can be closed, if it comes from a .bsp file then maybe I have some "broken" version. Unless you want to analyze it and find out what causes the problem?.

**Comment by tslashd** [comment]
There are maps with hookzones which are broken for some reason. 
If this issue was resolved, yes you can close it. 
I don't think that analyzing the map and fixing it would help as there would still be people using this `*.bsp` with the broken hookzones, better off just avoiding the hookzones for maps like that.

**Comment by DaLLuZZ** [comment]
you should delete checkpoint zone on this map to make start zone work properly

**Comment by DaLLuZZ** [comment]
that is wrong checkpoint-zone
https://github.com/surftimer/SurfTimer/blob/93a2343c9b11e0edd69ca646d79e7bdac73b77c4/scripts/mysql-files/ck_zones.sql#L5511
but it would be better if you delete all zones on `surf_utopia_njv` and rezone it yourself
